doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_pgsql'
    charset: utf8
    types:
      roles: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\RolesType
      uuid: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\UuidType
      password: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\PasswordType
      email: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\EmailType
      name: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\NameType
      token: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\TokenType
      state: LaSalle\StudentTeacher\User\User\Infrastructure\Persistence\Doctrine\Type\StateType
      status: LaSalle\StudentTeacher\Shared\Infrastructure\Persistence\Doctrine\Type\StatusType
      test_questions: LaSalle\StudentTeacher\Resource\ResourceStudentAnswer\Infrastructure\Persistence\Doctrine\Type\TestQuestionsType
      test_student_assumptions: LaSalle\StudentTeacher\Resource\ResourceStudentAnswer\Infrastructure\Persistence\Doctrine\Type\TestStudentAssumptionsType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/User/User/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\User\User\Domain\Aggregate
      RefreshToken:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/User/RefreshToken/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\User\RefreshToken\Domain\Aggregate
      UserConnection:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/User/Connection/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\User\Connection\Domain\Aggregate
      Category:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Resource/Category/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\Resource\Category\Domain\Aggregate
      Course:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Resource/Course/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\Resource\Course\Domain\Aggregate
      Unit:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Resource/Unit/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\Resource\Unit\Domain\Aggregate
      Resource:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Resource/Resource/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\Resource\Resource\Domain\Aggregate
      CoursePermission:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Resource/CoursePermission/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\Resource\CoursePermission\Domain\Aggregate
      ResourceStudentAnswer:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Resource/ResourceStudentAnswer/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: LaSalle\StudentTeacher\Resource\ResourceStudentAnswer\Domain\Aggregate