doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: utf8
        types:
            roles: LaSalle\GroupOne\Logging\Infrastructure\Persistence\Doctrine\Type\RolesType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            LaSalle\StudentTeacher:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'LaSalle\StudentTeacher\Entity'
                alias: LaSalle\StudentTeacher
