version: '3.5'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./etc/infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  php-fpm:
    container_name: fpm
    build:
      ./etc/infrastructure/php
    environment:
      - MESSENGER_TRANSPORT_DSN=amqp://rabbitmq:rabbitmq_pass@rabbitmq:5672/%2f/messages
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - backend

  php-consume:
    container_name: consumer
    build:
      ./etc/infrastructure/php
    environment:
      - MESSENGER_TRANSPORT_DSN=amqp://rabbitmq:rabbitmq_pass@rabbitmq:5672/%2f/messages
    entrypoint: /bin/sh
    command: "/usr/share/nginx/html/etc/infrastructure/php/extensions/message-consumer.sh"
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=studentteacher
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nimda
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    build:
      ./etc/infrastructure/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq_pass"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq:cached
    networks:
      - backend

volumes:
    rabbitmq:

networks:
  backend:
    driver: bridge
