version: '3.5'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  php-fpm:
    build:
      ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=teaching
    networks:
      - backend

networks:
  backend:
    driver: bridge
