version: '3.5'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  php-fpm:
    build:
      ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - backend

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=studentteacher
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nimda
    networks:
      - backend

networks:
  backend:
    driver: bridge
