fos_rest:
  body_listener: true
  param_fetcher_listener: force
  format_listener:
    enabled: true
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }
  view:
    view_response_listener: 'force'
    formats:
      json: true
      xml: false
      rss: false
    mime_types:
      json: ['application/json', 'application/x-json']
  routing_loader:
    default_format:  json
    include_format:  false
  exception:
    enabled: true
    codes:
      InvalidArgumentException: 400
      LaSalle\StudentTeacher\Resource\Application\Exception\CategoryAlreadyExists: 400
      LaSalle\StudentTeacher\Resource\Application\Exception\CategoryNotFound: 404
      LaSalle\StudentTeacher\Resource\Application\Exception\CourseNotFoundException: 404
      LaSalle\StudentTeacher\Shared\Application\Exception\PermissionDeniedException: 403
      LaSalle\StudentTeacher\User\Application\Exception\ConfirmationTokenIsExpiredException: 400
      LaSalle\StudentTeacher\User\Application\Exception\ConfirmationTokenNotFoundException: 404
      LaSalle\StudentTeacher\User\Application\Exception\ConnectionAlreadyExistsException: 400
      LaSalle\StudentTeacher\User\Application\Exception\ConnectionNotFoundException: 404
      LaSalle\StudentTeacher\User\Application\Exception\IncorrectConfirmationTokenException: 403
      LaSalle\StudentTeacher\User\Application\Exception\IncorrectPasswordException: 403
      LaSalle\StudentTeacher\User\Application\Exception\RefreshTokenIsExpiredException: 400
      LaSalle\StudentTeacher\User\Application\Exception\RefreshTokenNotFoundException: 404
      LaSalle\StudentTeacher\User\Application\Exception\RolesOfUsersEqualException: 400
      LaSalle\StudentTeacher\User\Application\Exception\UserAlreadyEnabledException: 400
      LaSalle\StudentTeacher\User\Application\Exception\UserAlreadyExistsException: 400
      LaSalle\StudentTeacher\User\Application\Exception\UsersAreEqualException: 400
      LaSalle\StudentTeacher\User\Application\Exception\UserNotFoundException: 404
      LaSalle\StudentTeacher\User\Application\Exception\UserNotEnabledException: 403
