fos_rest:
  body_listener: true
  param_fetcher_listener: force
  format_listener:
    enabled: true
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }
  view:
    view_response_listener: 'force'
    formats:
      json: true
      xml: false
      rss: false
    mime_types:
      json: ['application/json', 'application/x-json']
  routing_loader:
    default_format:  json
    include_format:  false
  exception:
    enabled: true
    codes:
      LaSalle\StudentTeacher\Shared\Application\Exception\InvalidArgumentValidationException: 400
      LaSalle\StudentTeacher\User\Application\Exception\IncorrectConfirmationTokenException: 403
      LaSalle\StudentTeacher\User\Application\Exception\IncorrectPasswordException: 403
      LaSalle\StudentTeacher\User\Application\Exception\UserAlreadyEnabledException: 400
      LaSalle\StudentTeacher\User\Application\Exception\UserAlreadyExistsException: 400
      LaSalle\StudentTeacher\User\Application\Exception\UserNotFoundException: 404
      LaSalle\StudentTeacher\User\Application\Exception\UserNotEnabledException: 403
      LaSalle\StudentTeacher\Token\Application\Exception\RefreshTokenIsExpiredException: 400
      LaSalle\StudentTeacher\Token\Application\Exception\RefreshTokenNotFoundException: 404