security:
    encoders:
        LaSalle\StudentTeacher\User\Infrastructure\Framework\Entity\SymfonyUser: bcrypt
    providers:
        fos_userbundle:
            id: LaSalle\StudentTeacher\User\Infrastructure\Framework\Provider\IdUserProvider

    firewalls:

        users:
            pattern:  ^/api/v1/users
            methods: ['GET', 'POST']
            anonymous: true

        api:
            pattern:   ^/api/v1
            anonymous: false
            stateless: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator