security:
    encoders:
        LaSalle\StudentTeacher\User\Infrastructure\Framework\Entity\SymfonyUser: bcrypt
    providers:
        fos_userbundle:
            id: LaSalle\StudentTeacher\User\Infrastructure\Framework\Provider\IdUserProvider

    firewalls:

        refresh:
            pattern:  ^/api/v1/users/token_refresh
            stateless: true
            anonymous: true

        sign_out:
            pattern:  ^/api/v1/users/sign_out
            stateless: true
            anonymous: true

        sign_in:
            pattern:  ^/api/v1/users/sign_in
            stateless: true
            anonymous: true

        sign_up:
            pattern:  ^/api/v1/users
            methods: [GET, POST]
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api/v1
            anonymous: false
            stateless: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator