# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  LaSalle\StudentTeacher\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  LaSalle\StudentTeacher\Shared\Infrastructure\Framework\Controller\:
    resource: '../src/Shared/Infrastructure/Framework/Controller'
    tags: ['controller.service_arguments']

  LaSalle\StudentTeacher\Shared\Domain\Event\DomainEventBus:
    alias: 'LaSalle\StudentTeacher\Shared\Infrastructure\Event\MessengerDomainEventBus'

  #LaSalle\StudentTeacher\Shared\Infrastructure\Event\MessengerDomainEventBus:
  #  arguments:
  #    $eventBus: '@event.bus'

  acme_api.event.jwt_created_listener:
    class: LaSalle\StudentTeacher\User\Infrastructure\Framework\Event\JWTCreatedListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

  #LaSalle\StudentTeacher\User\Application\Event\SendEmailConfirmationOnUserCreated:
  #  tags:
  #    - { name: 'kernel.event_listener', event: LaSalle\StudentTeacher\User\Domain\Event\UserCreatedDomainEvent }

  LaSalle\StudentTeacher\User\Application\Event\SendEmailConfirmationOnUserCreated:
          autoconfigure: false
          tags:
              - { name: messenger.message_handler, handles: LaSalle\StudentTeacher\User\Domain\Event\UserCreatedDomainEvent }

  LaSalle\StudentTeacher\User\Application\Event\SendEmailConfirmationOnEmailConfirmationRequestReceived:
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, handles: LaSalle\StudentTeacher\User\Domain\Event\EmailConfirmationRequestReceivedDomainEvent }

  LaSalle\StudentTeacher\User\Application\Event\SendPasswordResetOnPasswordRequestReceived:
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, handles: LaSalle\StudentTeacher\User\Domain\Event\PasswordResetRequestReceivedDomainEvent }
