name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make -C src composer-install keys-install

      - name: Start all the environment
        run: make -C src start

      - name: Wait for the environment to get up
        run: |
          while ! docker exec postgres pg_isready --user=root --host "127.0.0.1" > /dev/null 2> /dev/null ; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Run the tests
        run: make -C src parallel-test
